### ISSUE TITLE
同时发包冲突

### ISSUE THREAD

**Issue by miswanting** [miswanting/lib_Net#1]
Exception in thread 604e3a224b0d81dbbf33e92b560090e7:
Traceback (most recent call last):
  File "D:\Program Files\Anaconda3\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "D:\Program Files\Anaconda3\lib\threading.py", line 862, in run
    self._target(_self._args, *_self._kwargs)
  File "D:\Users\OneDrive\CODE\cloud\dist\lib_Net.py", line 135, in subServerStar
    package = self.recvJson(subServer['connection'])
  File "D:\Users\OneDrive\CODE\cloud\dist\lib_Net.py", line 423, in recvJson
    tmp = json.loads(self.recvMsg(connection))
  File "D:\Program Files\Anaconda3\lib\json__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\Anaconda3\lib\json\decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 170 (char 169)

**Comment by miswanting** [comment]
这个错误发生在 C 的线程上，是与 B 连接的服务器端。
发生在 setCloud 之后，可能是 C 多读取了一次包。
当时 B 在向全局分发 nodeOnline 包。
可能造成了冲突。
这解释了该 Bug 呈现出的偶然性的特点。

**Comment by miswanting** [comment]
在：
Exception in thread 768aa803901c268ae715db4949662657:
Traceback (most recent call last):
  File "D:\Program Files\Anaconda3\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "D:\Program Files\Anaconda3\lib\threading.py", line 862, in run
    self._target(_self._args, *_self._kwargs)
  File "D:\Users\OneDrive\CODE\cloud\dist\lib_Net.py", line 135, in subServerStar
    package = self.recvJson(subServer['connection'])
  File "D:\Users\OneDrive\CODE\cloud\dist\lib_Net.py", line 422, in recvJson
    tmp = json.loads(self.recvMsg(connection))
  File "D:\Program Files\Anaconda3\lib\json__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\Anaconda3\lib\json\decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 337 (char 336)
前，捕捉到Msg：
{"data": {"ip": "172.24.150.1", "randNode": "", "port": 50001, "lastNode": "3ed78dcbd7f5a1a27ba8bab76dbb938e", "nextNode": "79026139c1b798327f582ddd3bf1c9c9", "hash": "4900249b8862b1b9209f0d2d72d50e56"}, "to": ["everyone"], "request": "nodeOnline", "hash": "cc4be2cd33c09720c15ba2430301f58f", "from": "4900249b8862b1b9209f0d2d72d50e56"**}{**"data": {"ip": "172.24.150.1", "randNode": "", "port": 50002, "lastNode": "79026139c1b798327f582ddd3bf1c9c9", "nextNode": "", "hash": "3ed78dcbd7f5a1a27ba8bab76dbb938e"}, "to": ["everyone"], "request": "nodeOnline", "hash": "a9b91dd3b230f444327f6d7e11a78f66", "from": "3ed78dcbd7f5a1a27ba8bab76dbb938e"}
导致Json解码失败。
分析得：
包A：
"request": "nodeOnline"
"hash": "cc4be2cd33c09720c15ba2430301f58f"
"from": "4900249b8862b1b9209f0d2d72d50e56"
"to": ["everyone"]
包B：
"request": "nodeOnline"
"hash": "a9b91dd3b230f444327f6d7e11a78f66"
"from": "3ed78dcbd7f5a1a27ba8bab76dbb938e"
"to": ["everyone"]
再分析，包 A 是 B 原创的包，包 B 是 C 原创的包。
C 原创的包怎么会冲击自身服务器线程的 recv 方法呢？

[cmd.txt](https://github.com/miswanting/cloud/files/529120/cmd.txt)
[3ed78dcbd7f5a1a27ba8bab76dbb938e.txt](https://github.com/miswanting/cloud/files/529121/3ed78dcbd7f5a1a27ba8bab76dbb938e.txt)
[3fcd99a442a705668e0caad2c29f84b5.txt](https://github.com/miswanting/cloud/files/529123/3fcd99a442a705668e0caad2c29f84b5.txt)
[4900249b8862b1b9209f0d2d72d50e56.txt](https://github.com/miswanting/cloud/files/529124/4900249b8862b1b9209f0d2d72d50e56.txt)
[79026139c1b798327f582ddd3bf1c9c9.txt](https://github.com/miswanting/cloud/files/529122/79026139c1b798327f582ddd3bf1c9c9.txt)
