### ISSUE TITLE
类似的未知错误

### ISSUE THREAD

**Issue by miswanting** [miswanting/lib_Net#2]
Exception in thread LastStar:
Traceback (most recent call last):
  File "D:\Program Files\Anaconda3\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "D:\Program Files\Anaconda3\lib\threading.py", line 862, in run
    self._target(_self._args, *_self._kwargs)
  File "D:\Users\OneDrive\CODE\cloud\dist\lib_Net.py", line 308, in lastStar
    package = self.recvJson(self.lastSocket)
  File "D:\Users\OneDrive\CODE\cloud\dist\lib_Net.py", line 423, in recvJson
    tmp = json.loads(self.recvMsg(connection))
  File "D:\Program Files\Anaconda3\lib\json__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\Anaconda3\lib\json\decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 337 (char 336)

和 #1 错误类似，且未同时出现。

**Comment by miswanting** [comment]
当每步放慢的时候， #1 和 #2 错误都没出现，可以初步判断是信息冲突的问题。
